#ifndef GLOBALVARIABLES_H
#define GLOBALVARIABLES_H

const short ARRAY_SIZE_FOR_DRIVERS_NAME{1024};

const short AMOUNT_OF_PHYSICAL_MEMORY_BARS{4};
const short AMOUNT_OF_PHYSICAL_DISKS{4};
const short AMOUNT_OF_AUDIO_DEVICES{4};
const short AMOUNT_OF_NETWORK_CONTROLLERS{255};

#endif // GLOBALVARIABLES_H
